apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: localhpatest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vita-strong-deploy
  minReplicas: 2
  maxReplicas: 7
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5